workspace:
  base: /drone
  path: src/git.winshare-edu.com/winshare/winshare-yuxin-school
  
pipeline:
  clone:
    image: plugins/git
    recursive: true
    tags: true
  build:
    image: maven:3-jdk-7-alpine
    volumes:
      - /data/maven:/root/.m2
    commands:
      - cp .settings.xml /root/.m2/settings.xml
      - mvn clean install -Dmaven.test.skip=true
