(function(){
    $(function(){
        //带颜色图标
        $(".img_hover1").on("mouseenter","img.qq",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/QQ_hover.png");
        }).on("mouseleave","img.qq",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/QQ.png")
        }).on("mouseenter","img.wx",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/WX_hover.png");
        }).on("mouseleave","img.wx",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/WX.png")
        }).on("mouseenter","img.wb",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/WB_hover.png");
        }).on("mouseleave","img.wb",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/WB.png")
        });
        //不带颜色图标
        $(".img-hover").on("mouseenter","img.qq",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/QQ_white.png");
        }).on("mouseleave","img.qq",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/QQ_.png")
        }).on("mouseenter","img.wx",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/WX_white.png");
        }).on("mouseleave","img.wx",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/WX_.png")
        }).on("mouseenter","img.wb",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/WB_white.png");
        }).on("mouseleave","img.wb",function(){
            $(this).attr("src",rootPath+"/images/footer_icon/WB_.png")
        });
        //鼠标放在微信图标二维码显示
        $(".weixin-logo").on("mouseenter",function(){
            $(".pop-ewm").show();
        }).on("mouseleave",function(){
            $(".pop-ewm").hide();
        })
    })
})(jQuery)
